//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: MNIST.ice
//  Source: MNIST.idsl
//
//******************************************************************
#ifndef MNIST_ICE
#define MNIST_ICE
module MNIST
{
	struct MNISTResult
	{
		int number;
		float confidence;
	};
	interface MNIST
	{
		MNISTResult get_number ();
		MNISTResult process_image ();
	};
};

#endif
